### ISSUE TITLE
SIGSEGV during normal usage

### ISSUE THREAD

**Issue by kodeninja** [vmware-tanzu/octant#1109]
**What steps did you take and what happened:**
The `octant` cli just crashed with a `SIGSEGV` during normal usage. I don't recall doing anything out of the ordinary to have caused this.

**What did you expect to happen:**
The cli would continue to work as expected.

**Anything else you would like to add:**
Stacktrace:
```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1572fea]

goroutine 3404975 [running]:
github.com/json-iterator/go.(*Stream).WriteStringWithHTMLEscaped(0xc002a87f20, 0x0, 0xe)
	/private/tmp/octant-20200704-95199-1ad38ta/src/github.com/vmware-tanzu/octant/vendor/github.com/json-iterator/go/stream_str.go:227 +0x7a
github.com/json-iterator/go.(*htmlEscapedStringEncoder).Encode(0x4a6c398, 0xc001d543f8, 0xc002a87f20)
	/private/tmp/octant-20200704-95199-1ad38ta/src/github.com/vmware-tanzu/octant/vendor/github.com/json-iterator/go/config.go:263 +0x41
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc0013db9b0, 0xc001d543e8, 0xc002a87f20)
	/private/tmp/octant-20200704-95199-1ad38ta/src/github.com/vmware-tanzu/octant/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:110 +0x86
github.com/json-iterator/go.(*structEncoder).Encode(0xc0013dba40, 0xc001d543e8, 0xc002a87f20)
	/private/tmp/octant-20200704-951:158 +0x3b8
github.com/json-iterator/go.(*sliceEncoder).Encode(0xc000912600, 0xc001d42498, 0xc002a87f20)
	/private/tmp/octant-20200704-95199-1ad38ta/src/github.com/vmware-tanzu/octant/vendor/github.com/json-iterator/go/reflect_slice.go:42 +0x153
github.com/json-iterator/go.(*placeholderEncoder).Encode(0xc0006e7130, 0xc001d42498, 0xc002a87f20)
	/private/tmp/octant-20200704-95199-1ad38ta/src/github.com/vmware-tanzu/octant/vendor/github.com/json-iterator/go/reflect.go:332 +0x47
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc0012feea0, 0xc001d42408, 0xc002a87f20)
	/private/tmp/octant-20200704-95199-1ad38ta/src/github.com/vmware-tanzu/octant/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:110 +0x86
github.com/json-iterator/go.(*structEncoder).Encode(0xc0012ffaa0, 0xc001d42408, 0xc002a87f20)
	/private/tmp/octant-20200704-95199-1ad38ta/src/github.com/vmware-tanzu/octant/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:158 +0x3b8
github.com/json-iterator/go.(*sliceEncoder).Encode(0xc000022b80, 0xc002800148, 0xc002a87f20)
	/private/tmp/octant-20200704-95199-1ad38ta/src/github.com/vmware-tanzu/octant/vendor/github.com/json-iterator/go/reflect_slice.go:42 +0x153
github.com/json-iterator/go.(*placeholderEncoder).Encode(0xc000a23640, 0xc002800148, 0xc002a87f20)
	/private/tmp/octant-20200704-95199-1ad38ta/src/github.com/vmware-tanzu/octant/vendor/github.com/json-iterator/go/reflect.go:332 +0x47
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc00025c1b0, 0xc002800118, 0xc002a87f20)
	/private/tmp/octant-20200704-95199-1ad38ta/src/github.com/vmware-tanzu/octant/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:110 +0x86
github.com/json-iterator/go.(*structEncoder).Encode(0xc00089b1a0, 0xc002800118, 0xc002a87f20)
	/private/tmp/octant-20200704-95199-1ad38ta/src/github.com/vmware-tanzu/octant/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:158 +0x3b8
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc000416a20, 0xc002800000, 0xc002a87f20)
	/private/tmp/octant-20200704-95199-1ad38ta/src/github.com/vmware-tanzu/octant/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:110 +0x86
github.com/json-iterator/go.(*structEncoder).Encode(0xc000416ae0, 0xc002800000, 0xc002a87f20)
	/private/tmp/octant-20200704-95199-1ad38ta/src/github.com/vmware-tanzu/octant/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:158 +0x3b8
github.com/json-iterator/go.(*OptionalEncoder).Encode(0xc0013427f0, 0xc00165a118, 0xc002a87f20)
	/private/tmp/octant-20200704-95199-1ad38ta/src/github.com/vmware-tanzu/octant/vendor/github.com/json-iterator/go/reflect_optional.go:74 +0xeb
github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc001342800, 0xc002800000, 0xc002a87f20)
	/private/tmp/octant-20200704-95199-1ad38ta/src/github.com/vmware-tanzu/octant/vendor/github.com/json-iterator/go/reflect.go:219 +0x68
github.com/json-iterator/go.(*Stream).WriteVal(0xc002a87f20, 0x25a6880, 0xc002800000)
	/private/tmp/octant-20200704-95199-1ad38ta/src/github.com/vmware-tanzu/octant/vendor/github.com/json-iterator/go/reflect.go:98 +0x146
github.com/json-iterator/go.(*frozenConfig).Marshal(0xc00022d5e0, 0x25a6880, 0xc002800000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/octant-20200704-95199-1ad38ta/src/github.com/vmware-tanzu/octant/vendor/github.com/json-iterator/go/config.go:299 +0xaf
k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).doEncode(0xc000e50780, 0x3d3ade0, 0xc002800000, 0x3d2c360, 0xc00232f380, 0x0, 0x8)
	/private/tmp/octant-20200704-95199-1ad38ta/src/github.com/vmware-tanzu/octant/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go:305 +0x7c
k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Encode(0xc000e50780, 0x3d3ade0, 0xc002800000, 0x3d2c360, 0xc00232f380, 0xc0018d0fd0, 0x0)
	/private/tmp/octant-20200704-95199-1ad38ta/src/github.com/vmware-tanzu/octant/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go:300 +0x172
github.com/vmware-tanzu/octant/internal/util/kubernetes.SerializeToString(0x3d3ade0, 0xc002800000, 0x100e586, 0xc002a87e60, 0x60, 0x58)
	/private/tmp/octant-20200704-95199-1ad38ta/src/github.com/vmware-tanzu/octant/internal/util/kubernetes/object.go:59 +0x1ab
github.com/vmware-tanzu/octant/pkg/view/component.(*Editor).SetValueFromObject(0xc002a87e60, 0x3d3ade0, 0xc002800000, 0x0, 0x0)
	/private/tmp/octant-20200704-95199-1ad38ta/src/github.com/vmware-tanzu/octant/pkg/view/component/editor.go:43 +0x4d
github.com/vmware-tanzu/octant/internal/mo(0xc0015d2270, 0xc002800000, 0xc0015d2270, 0x0)
	/private/tmp/octant-20200704-95199-1ad38ta/src/github.com/vmware-tanzu/octant/internal/modules/overview/yamlviewer/yamlviewer.go:43 +0x1ca
github.com/vmware-tanzu/octant/internal/modules/overview/yamlviewer.ToComponent(0x3d3ade0, 0xc002800000, 0x3, 0x3, 0x200c0006728a0)
	/private/tmp/octant-20200704-95199-1ad38ta/src/github.com/vmware-tanzu/octant/internal/modules/overview/yamlviewer/yamlviewer.go:21 +0xa0
github.com/vmware-tanzu/octant/internal/describer.YAMLViewerTab(0x3d6cde0, 0xc0021ad1d0, 0x3d3ade0, 0xc002800000, 0x3d8f1a0, 0xc001326000, 0x3d8a0e0, 0xc000c25dc0, 0xc0021ad350, 0x3d2aa00, ...)
	/private/tmp/octant-20200704-95199-1ad38ta/src/github.com/vmware-tanzu/octant/internal/describer/tab.go:101 +0x39
github.com/vmware-tanzu/octant/internal/describer.ObjectTabsGenerator.Generate.func1(0x103e0c6, 0x3b6f770)
	/private/tmp/octant-20200704-95199-1ad38ta/src/github.com/vmware-tanzu/octant/internal/describer/tab_generator.go:82 +0xd6
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc001e2e5a0, 0xc0006ea600)
	/private/tmp/octant-20200704-95199-1ad38ta/src/github.com/vmware-tanzu/octant/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	/private/tmp/octant-20200704-95199-1ad38ta/src/github.com/vmware-tanzu/octant/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x66
```

**Environment:**

- Octant version (use `octant version`): 
```bash
Version:  0.13.1
Git commit:  72c5ea94283ab48cc6c2b7e91d7c901af031ecb3
Built:  2020-07-04T18:26:42Z
```
- Kubernetes version (use `kubectl version`):
```bash
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:50:54Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-f459c0", GitCommit:"f459c0672169dd35e77af56c24556530a05e9ab1", GitTreeState:"clean", BuildDate:"2020-03-18T04:24:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):
```bash
ProductName:	Mac OS X
ProductVersion:	10.14.5
BuildVersion:	18F132
```

**Comment by wwitzel3** [comment]
Interesting, there are a few reports of this same issue reported in the upstream package `json-iterator`

- https://github.com/json-iterator/go/issues/298
- https://github.com/json-iterator/go/issues/233

Octant doesn't use this library directly, so it will take some investigation to determine what about our usage of `k8s.io/apimachinery/pkg/runtime/serializer/json NewSerializerWithOptions.Encode` is causing this panic.

 @kodeninja 
 - do you have a scenario or set of steps in which you can reproduce this panic every time?
 - was Octant running for a long or short period of time?
 - how many Tabs/Windows were open to Octant when this happened?

**Comment by kodeninja** [comment]
@wwitzel3 

- I can certainly start octant and just keep the cli running in the background. There was really nothing special I was doing when this crash happened.
- I think octant had been running for an hour or so at the time of the crash.
-  I did have the GUI open in FF (1 Tab), and Chrome (3-4 Tabs) at the time. Actually, this was also for a reason (perhaps there's  already an issue for it). In Chrome, the `Terminal` tab container selection dropdown keeps fidgeting when you have more than one containers. This does not happen in FF, though. As you can see in the animation below, I'm unable to select the second container.

![octant-chrome-terminal-dropdown-issue](https://user-images.githubusercontent.com/817245/87484194-6c681100-c5ea-11ea-88cf-cb6025ecb17f.gif)

**Comment by wwitzel3** [comment]
Thank you, I'll open an issue for the select drop down on the terminal.

I'll keep you posted on what we find with the panic.
