### ISSUE TITLE
Panic while executing command in terminal

### ISSUE THREAD

**Issue by Anganthier** [vmware-tanzu/octant#1502]
**What steps did you take and what happened:**

I am running 0.16.1 octant in a chrome browser. I wasn't able to reproduce the error repeating the same steps.

I started a terminal on a pod and executed two commands: (Workloads->Pods->gitea  -- Terminal)

```sh
/ # ls
app    bin    data   dev    etc    home   lib    media  mnt    opt    proc   root   run    sbin   srv    sys    tmp    usr    var
/ # ls -la
total 80
drwxr-xr-x    1 root     root          4096 Sep 16 06:30 .
drwxr-xr-x    1 root     root          4096 Sep 16 06:30 ..
-rwxr-xr-x    1 root     root             0 Sep 16 06:30 .dockerenv
drwxr-xr-x    1 root     root          4096 Jul 28 21:33 app
drwxr-xr-x    1 root     root          4096 Jul 28 21:33 bin
drwxrwxrwx    6 root     root          4096 May 16 10:30 data
drwxr-xr-x    5 root     root           360 Sep 16 06:30 dev
drwxr-xr-x    1 root     root          4096 Sep 16 06:30 etc
drwxr-xr-x    2 root     root          4096 Apr 23 06:25 home
total 80
drwxr-xr-x    1 root     root          4096 Sep 16 06:30 .
drwxr-xr-x    1 root     root          4096 Sep 16 06:30 ..
-rwxr-xr-x    1 root     root             0 Sep 16 06:30 .dockerenv
drwxr-xr-x    1 root     root          4096 Jul 28 21:33 app
drwxr-xr-x    1 root     root          4096 Jul 28 21:33 bin
drwxrwxrwx    6 root     root          4096 May 16 10:30 data
drwxr-xr-x    5 root     root           360 Sep 16 06:30 dev
drwxr-xr-x    1 root     root          4096 Sep 16 06:30 etc
drwxr-xr-x    2 root     root          4096 Apr 23 06:25 home
```

**What did you expect to happen:**
I just expected ls -la to show the list of files just once not twice and I expected the command prompt afterwards.

**Anything else you would like to add:**
The following panic showed up:

```
E1014 19:45:23.614843  594797 runtime.go:78] Observed a panic: runtime.boundsError{x:1328, y:1172, signed:true, code:0x3} (runtime error: slice bounds out of range [1328:1172])
goroutine 63504 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1bf0660, 0xc00a4a0c40)
	/__w/octant/octant/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/__w/octant/octant/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x1bf0660, 0xc00a4a0c40)
	/usr/local/go/src/runtime/panic.go:967 +0x15d
bytes.(*Buffer).grow(0xc00843bf50, 0xd9, 0x0)
	/usr/local/go/src/bytes/buffer.go:137 +0x2d6
bytes.(*Buffer).Write(0xc00843bf50, 0xc001ba2000, 0xd9, 0x8000, 0x1, 0x1, 0x0)
	/usr/local/go/src/bytes/buffer.go:172 +0xdc
github.com/vmware-tanzu/octant/internal/terminal.(*pty).Write(0xc001510230, 0xc001ba2000, 0xd9, 0x8000, 0x0, 0x0, 0x0)
	/__w/octant/octant/internal/terminal/instance.go:82 +0x175
io.copyBuffer(0x7fb6353f9918, 0xc001510230, 0x7fb6343f1698, 0xc00a2bbae0, 0xc001ba2000, 0x8000, 0x8000, 0x14cd199, 0x0, 0x0)
	/usr/local/go/src/io/io.go:407 +0x1fb
io.Copy(...)
	/usr/local/go/src/io/io.go:364
k8s.io/client-go/tools/remotecommand.(*streamProtocolV2).copyStdout.func1(0xc00a1afca0, 0xc0103e4ab0)
	/__w/octant/octant/vendor/k8s.io/client-go/tools/remotecommand/v2.go:146 +0xc4
created by k8s.io/client-go/tools/remotecommand.(*streamProtocolV2).copyStdout
	/__w/octant/octant/vendor/k8s.io/client-go/tools/remotecommand/v2.go:142 +0x6c
panic: runtime error: slice bounds out of range [1328:1172] [recovered]
	panic: runtime error: slice bounds out of range [1328:1172]

goroutine 63504 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/__w/octant/octant/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x1bf0660, 0xc00a4a0c40)
	/usr/local/go/src/runtime/panic.go:967 +0x15d
bytes.(*Buffer).grow(0xc00843bf50, 0xd9, 0x0)
	/usr/local/go/src/bytes/buffer.go:137 +0x2d6
bytes.(*Buffer).Write(0xc00843bf50, 0xc001ba2000, 0xd9, 0x8000, 0x1, 0x1, 0x0)
	/usr/local/go/src/bytes/buffer.go:172 +0xdc
github.com/vmware-tanzu/octant/internal/terminal.(*pty).Write(0xc001510230, 0xc001ba2000, 0xd9, 0x8000, 0x0, 0x0, 0x0)
	/__w/octant/octant/internal/terminal/instance.go:82 +0x175
io.copyBuffer(0x7fb6353f9918, 0xc001510230, 0x7fb6343f1698, 0xc00a2bbae0, 0xc001ba2000, 0x8000, 0x8000, 0x14cd199, 0x0, 0x0)
	/usr/local/go/src/io/io.go:407 +0x1fb
io.Copy(...)
	/usr/local/go/src/io/io.go:364
k8s.io/client-go/tools/remotecommand.(*streamProtocolV2).copyStdout.func1(0xc00a1afca0, 0xc0103e4ab0)
	/__w/octant/octant/vendor/k8s.io/client-go/tools/remotecommand/v2.go:146 +0xc4
created by k8s.io/client-go/tools/remotecommand.(*streamProtocolV2).copyStdout
	/__w/octant/octant/vendor/k8s.io/client-go/tools/remotecommand/v2.go:142 +0x6c
```

**Environment:**

- Octant version (use `octant version`):  
Version:  0.16.1
Git commit:  8aebb34922f83894fb02ad393740e96ee1b3d8fe
Built:  2020-10-07T23:36:32Z

- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):
Linux Mint 20

**Comment by wwitzel3** [comment]
Hi @Anganthier thank you for reporting this, can you provide the version of gitea or even better the deployment YAML you were using?

Also is this happening every single time or is this something that is happening randomly?

**Comment by Anganthier** [comment]
Hi,

I can't reproduce the error. It seems that clicking around to different views before changing to the gitea terminal had a part in that error.

I installed gitea using a helm chart:
```sh
helm repo add k8s-land https://charts.k8s.land
helm install gitea k8s-land/gitea -f values.yaml
```

Here is the important part of that values.yaml file:
```yaml
images:
  registry: docker.io
  gitea: "gitea/gitea:1.12.3"
  #gitea: "gitea/gitea:1.11.5"
  memcached: "memcached:1.5.19-alpine"
  pullPolicy: IfNotPresent
```

And a description of the deployment:
```
Name:                   gitea-gitea
Namespace:              default
CreationTimestamp:      Sat, 16 May 2020 12:24:33 +0200
Labels:                 app=gitea-gitea
                        chart=gitea-1.3.3
                        heritage=Helm
                        release=gitea
Annotations:            deployment.kubernetes.io/revision: 6
Selector:               app=gitea-gitea
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:       app=gitea-gitea
  Annotations:  backup.velero.io/backup-volumes: gitea-data
  Init Containers:
   init:
    Image:      gitea/gitea:1.12.3
    Port:       <none>
    Host Port:  <none>
    Command:
      /bin/sh
      -c
      mkdir -p /datatmp/gitea/conf
      if [ ! -f /datatmp/gitea/conf/app.ini ]; then
        sed "s/MARIADB_PASSWORD/${MARIADB_PASSWORD}/g" < /etc/gitea/app.ini > /datatmp/gitea/conf/app.ini
      fi
    Environment:
      MARIADB_PASSWORD:  <set to the key 'db-password' in secret 'gitea-externaldb'>  Optional: false
      SCRIPT:            mkdir -p /datatmp/gitea/conf
                         if [ ! -f /datatmp/gitea/conf/app.ini ]; then
                           sed "s/MARIADB_PASSWORD/${MARIADB_PASSWORD}/g" < /etc/gitea/app.ini > /datatmp/gitea/conf/app.ini
                         fi
    Mounts:
      /datatmp from gitea-data (rw)
      /etc/gitea from gitea-config (rw)
  Containers:
   gitea:
    Image:       gitea/gitea:1.12.3
    Ports:       22/TCP, 3000/TCP
    Host Ports:  0/TCP, 0/TCP
    Limits:
      cpu:     2
      memory:  4Gi
    Requests:
      cpu:      1
      memory:   2Gi
    Liveness:   tcp-socket :http delay=200s timeout=1s period=10s #success=1 #failure=10
    Readiness:  tcp-socket :http delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment:
      DATABASE_PASSWORD:  <set to the key 'db-password' in secret 'gitea-externaldb'>  Optional: false
    Mounts:
      /data from gitea-data (rw)
      /etc/gitea from gitea-config (rw)
   memcached:
    Image:      memcached:1.5.19-alpine
    Port:       11211/TCP
    Host Port:  0/TCP
    Command:
      memcached
      -m 64
      -o
      modern
      -v
    Requests:
      cpu:        100m
      memory:     512Mi
    Liveness:     tcp-socket :memcache delay=30s timeout=5s period=10s #success=1 #failure=3
    Readiness:    tcp-socket :memcache delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:       <none>
  Volumes:
   gitea-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  gitea-gitea
    ReadOnly:   false
   gitea-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      gitea-gitea
    Optional:  false
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   gitea-gitea-8456bbdf7 (1/1 replicas created)
Events:          <none>
```

And the complete gitea.yaml file of the pod:

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    backup.velero.io/backup-volumes: gitea-data
    cni.projectcalico.org/podIP: 10.0.150.116/32
    cni.projectcalico.org/podIPs: 10.0.150.116/32
  creationTimestamp: "2020-09-16T06:20:10Z"
  generateName: gitea-gitea-8456bbdf7-
  labels:
    app: gitea-gitea
    pod-template-hash: 8456bbdf7
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:backup.velero.io/backup-volumes: {}
        f:generateName: {}
        f:labels:
          .: {}
          f:app: {}
          f:pod-template-hash: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"2df2ba64-f0ec-4b28-b16d-b8207c12e94a"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:containers:
          k:{"name":"gitea"}:
            .: {}
            f:env:
              .: {}
              k:{"name":"DATABASE_PASSWORD"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:secretKeyRef:
                    .: {}
                    f:key: {}
                    f:name: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:livenessProbe:
              .: {}
              f:failureThreshold: {}
              f:initialDelaySeconds: {}
              f:periodSeconds: {}
              f:successThreshold: {}
              f:tcpSocket:
                .: {}
                f:port: {}
              f:timeoutSeconds: {}
            f:name: {}
            f:ports:
              .: {}
              k:{"containerPort":22,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:name: {}
                f:protocol: {}
              k:{"containerPort":3000,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:name: {}
                f:protocol: {}
            f:readinessProbe:
              .: {}
              f:failureThreshold: {}
              f:initialDelaySeconds: {}
              f:periodSeconds: {}
              f:successThreshold: {}
              f:tcpSocket:
                .: {}
                f:port: {}
              f:timeoutSeconds: {}
            f:resources:
              .: {}
              f:limits:
                .: {}
                f:cpu: {}
                f:memory: {}
              f:requests:
                .: {}
                f:cpu: {}
                f:memory: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/data"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/etc/gitea"}:
                .: {}
                f:mountPath: {}
                f:name: {}
          k:{"name":"memcached"}:
            .: {}
            f:command: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:livenessProbe:
              .: {}
              f:failureThreshold: {}
              f:initialDelaySeconds: {}
              f:periodSeconds: {}
              f:successThreshold: {}
              f:tcpSocket:
                .: {}
                f:port: {}
              f:timeoutSeconds: {}
            f:name: {}
            f:ports:
              .: {}
              k:{"containerPort":11211,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:name: {}
                f:protocol: {}
            f:readinessProbe:
              .: {}
              f:failureThreshold: {}
              f:initialDelaySeconds: {}
              f:periodSeconds: {}
              f:successThreshold: {}
              f:tcpSocket:
                .: {}
                f:port: {}
              f:timeoutSeconds: {}
            f:resources:
              .: {}
              f:requests:
                .: {}
                f:cpu: {}
                f:memory: {}
            f:securityContext:
              .: {}
              f:runAsUser: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:initContainers:
          .: {}
          k:{"name":"init"}:
            .: {}
            f:command: {}
            f:env:
              .: {}
              k:{"name":"MARIADB_PASSWORD"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:secretKeyRef:
                    .: {}
                    f:key: {}
                    f:name: {}
              k:{"name":"SCRIPT"}:
                .: {}
                f:name: {}
                f:value: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:resources: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/datatmp"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/etc/gitea"}:
                .: {}
                f:mountPath: {}
                f:name: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext: {}
        f:terminationGracePeriodSeconds: {}
        f:volumes:
          .: {}
          k:{"name":"gitea-config"}:
            .: {}
            f:configMap:
              .: {}
              f:defaultMode: {}
              f:name: {}
            f:name: {}
          k:{"name":"gitea-data"}:
            .: {}
            f:name: {}
            f:persistentVolumeClaim:
              .: {}
              f:claimName: {}
    manager: kube-controller-manager
    operation: Update
    time: "2020-09-16T06:20:10Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:cni.projectcalico.org/podIP: {}
          f:cni.projectcalico.org/podIPs: {}
    manager: calico
    operation: Update
    time: "2020-09-16T06:30:28Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:initContainerStatuses: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"10.0.150.116"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    time: "2020-09-16T06:30:43Z"
  name: gitea-gitea-8456bbdf7-xc2l8
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: gitea-gitea-8456bbdf7
    uid: 2df2ba64-f0ec-4b28-b16d-b8207c12e94a
  resourceVersion: "85791808"
  selfLink: /api/v1/namespaces/default/pods/gitea-gitea-8456bbdf7-xc2l8
  uid: 27fdc01c-2db8-46c5-a056-f3078607d21e
spec:
  containers:
  - env:
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          key: db-password
          name: gitea-externaldb
    image: gitea/gitea:1.12.3
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 10
      initialDelaySeconds: 200
      periodSeconds: 10
      successThreshold: 1
      tcpSocket:
        port: http
      timeoutSeconds: 1
    name: gitea
    ports:
    - containerPort: 22
      name: ssh
      protocol: TCP
    - containerPort: 3000
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      tcpSocket:
        port: http
      timeoutSeconds: 1
    resources:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: "1"
        memory: 2Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /data
      name: gitea-data
    - mountPath: /etc/gitea
      name: gitea-config
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-67tl5
      readOnly: true
  - command:
    - memcached
    - -m 64
    - -o
    - modern
    - -v
    image: memcached:1.5.19-alpine
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      tcpSocket:
        port: memcache
      timeoutSeconds: 5
    name: memcached
    ports:
    - containerPort: 11211
      name: memcache
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      tcpSocket:
        port: memcache
      timeoutSeconds: 1
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
    securityContext:
      runAsUser: 1000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-67tl5
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: image-pull-secret
  initContainers:
  - command:
    - /bin/sh
    - -c
    - |-
      mkdir -p /datatmp/gitea/conf
      if [ ! -f /datatmp/gitea/conf/app.ini ]; then
        sed "s/MARIADB_PASSWORD/${MARIADB_PASSWORD}/g" < /etc/gitea/app.ini > /datatmp/gitea/conf/app.ini
      fi
    env:
    - name: MARIADB_PASSWORD
      valueFrom:
        secretKeyRef:
          key: db-password
          name: gitea-externaldb
    - name: SCRIPT
      value: |-
        mkdir -p /datatmp/gitea/conf
        if [ ! -f /datatmp/gitea/conf/app.ini ]; then
          sed "s/MARIADB_PASSWORD/${MARIADB_PASSWORD}/g" < /etc/gitea/app.ini > /datatmp/gitea/conf/app.ini
        fi
    image: gitea/gitea:1.12.3
    imagePullPolicy: IfNotPresent
    name: init
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /datatmp
      name: gitea-data
    - mountPath: /etc/gitea
      name: gitea-config
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-67tl5
      readOnly: true
  nodeName: worker-1
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: gitea-data
    persistentVolumeClaim:
      claimName: gitea-gitea
  - configMap:
      defaultMode: 420
      name: gitea-gitea
    name: gitea-config
  - name: default-token-67tl5
    secret:
      defaultMode: 420
      secretName: default-token-67tl5
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-09-16T06:30:29Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-09-16T06:30:43Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-09-16T06:30:43Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-09-16T06:20:10Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://e8c0b1c31c74f8457056586c4695d4662d12a94629c5e21e0a026286cec742b3
    image: gitea/gitea:1.12.3
    imageID: docker-pullable://gitea/gitea@sha256:a94e3542a9b5967d9ba3b7d2eb8630c1d7b61776326addcfd4fba6ab4f4f91db
    lastState: {}
    name: gitea
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-09-16T06:30:29Z"
  - containerID: docker://7636b1e720c9a0e8c5fdb0f0f00e2f1a8d28ccba1a82e96d28e4abec93e4bbb9
    image: memcached:1.5.19-alpine
    imageID: docker-pullable://memcached@sha256:37c28f53d30d7b8d273eb86465f92932cac6662477075c85d4bc8d0ceb349f96
    lastState: {}
    name: memcached
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-09-16T06:30:30Z"
  hostIP: 172.17.2.2
  initContainerStatuses:
  - containerID: docker://b87c04dcd5ef03703b36059c50af79ff94f894117e8703e593b8533ca64a4e28
    image: gitea/gitea:1.12.3
    imageID: docker-pullable://gitea/gitea@sha256:a94e3542a9b5967d9ba3b7d2eb8630c1d7b61776326addcfd4fba6ab4f4f91db
    lastState: {}
    name: init
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: docker://b87c04dcd5ef03703b36059c50af79ff94f894117e8703e593b8533ca64a4e28
        exitCode: 0
        finishedAt: "2020-09-16T06:30:28Z"
        reason: Completed
        startedAt: "2020-09-16T06:30:28Z"
  phase: Running
  podIP: 10.0.150.116
  podIPs:
  - ip: 10.0.150.116
  qosClass: Burstable
  startTime: "2020-09-16T06:20:10Z"
```

**Comment by wwitzel3** [comment]
Thank you for providing that.

I have another question, do you access this cluster via VPN or jump box port-forward or do you have direct access? After looking at the original error some more and exploring the code, it reads like this may have been due to a connection error during the streaming of the output from the Kubernetes API

**Comment by Anganthier** [comment]
Hi,

yes. I do access the cluster through a OpenVPN connection. My other network sessions across that vpn were still functional though, but I can't rule out that possibility. That might also explain why I can't reproduce the error.

**Comment by wwitzel3** [comment]
I'm going to close this for now, please don't hesitate to reopen it if you run in to the problem again.
