### ISSUE TITLE
Octant crash on Windows : panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by survivant** [vmware-tanzu/octant#2798]
I was looking for a pod logs and I remove the helm chart from command line.  I obtain this error "sometime"

````
2021-08-27T07:44:57.278-0400    INFO    plugin/manager.go:372   watching for new JavaScript plugins in ["C:\\Users\\sd003526\\AppData\\Local\\octant\\plugins"]
2021-08-27T07:44:57.365-0400    INFO    dash/dash.go:546        Dashboard is available at http://127.0.0.1:7777

W0827 07:45:01.221944   21332 reflector.go:436] /__w/octant/octant/internal/objectstore/dynamic_cache.go:390: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
W0827 07:45:02.368205   21332 reflector.go:436] /__w/octant/octant/internal/objectstore/dynamic_cache.go:390: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
W0827 07:45:04.163877   21332 reflector.go:436] /__w/octant/octant/internal/objectstore/dynamic_cache.go:390: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
W0827 07:45:09.382583   21332 reflector.go:436] /__w/octant/octant/internal/objectstore/dynamic_cache.go:390: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
W0827 07:45:18.788068   21332 reflector.go:436] /__w/octant/octant/internal/objectstore/dynamic_cache.go:390: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
W0827 07:45:38.823302   21332 reflector.go:436] /__w/octant/octant/internal/objectstore/dynamic_cache.go:390: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
W0827 07:46:23.277041   21332 reflector.go:436] /__w/octant/octant/internal/objectstore/dynamic_cache.go:390: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
W0827 07:47:17.412722   21332 reflector.go:436] /__w/octant/octant/internal/objectstore/dynamic_cache.go:390: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
W0827 07:47:53.873602   21332 reflector.go:436] /__w/octant/octant/internal/objectstore/dynamic_cache.go:390: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
W0827 07:48:41.444539   21332 reflector.go:436] /__w/octant/octant/internal/objectstore/dynamic_cache.go:390: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
W0827 07:49:14.494630   21332 reflector.go:436] /__w/octant/octant/internal/objectstore/dynamic_cache.go:390: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
W0827 07:49:54.905764   21332 reflector.go:436] /__w/octant/octant/internal/objectstore/dynamic_cache.go:390: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
W0827 07:50:27.861286   21332 reflector.go:436] /__w/octant/octant/internal/objectstore/dynamic_cache.go:390: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
W0827 07:51:22.844332   21332 reflector.go:436] /__w/octant/octant/internal/objectstore/dynamic_cache.go:390: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
W0827 07:52:09.968333   21332 reflector.go:436] /__w/octant/octant/internal/objectstore/dynamic_cache.go:390: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
W0827 07:53:02.337534   21332 reflector.go:436] /__w/octant/octant/internal/objectstore/dynamic_cache.go:390: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
W0827 07:53:32.946698   21332 reflector.go:436] /__w/octant/octant/internal/objectstore/dynamic_cache.go:390: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
W0827 07:54:26.900587   21332 reflector.go:436] /__w/octant/octant/internal/objectstore/dynamic_cache.go:390: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
W0827 07:55:17.854109   21332 reflector.go:436] /__w/octant/octant/internal/objectstore/dynamic_cache.go:390: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
W0827 07:55:49.713621   21332 reflector.go:436] /__w/octant/octant/internal/objectstore/dynamic_cache.go:390: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
W0827 07:56:23.571765   21332 reflector.go:436] /__w/octant/octant/internal/objectstore/dynamic_cache.go:390: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
W0827 07:57:11.325559   21332 reflector.go:436] /__w/octant/octant/internal/objectstore/dynamic_cache.go:390: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
W0827 07:57:54.065423   21332 reflector.go:436] /__w/octant/octant/internal/objectstore/dynamic_cache.go:390: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
W0827 07:58:28.098568   21332 reflector.go:436] /__w/octant/octant/internal/objectstore/dynamic_cache.go:390: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
W0827 07:59:19.141650   21332 reflector.go:436] /__w/octant/octant/internal/objectstore/dynamic_cache.go:390: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
W0827 07:59:53.878315   21332 reflector.go:436] /__w/octant/octant/internal/objectstore/dynamic_cache.go:390: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
W0827 08:00:53.159732   21332 reflector.go:436] /__w/octant/octant/internal/objectstore/dynamic_cache.go:390: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
W0827 08:01:43.961475   21332 reflector.go:436] /__w/octant/octant/internal/objectstore/dynamic_cache.go:390: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
W0827 08:02:15.504756   21332 reflector.go:436] /__w/octant/octant/internal/objectstore/dynamic_cache.go:390: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xc7c0df]

goroutine 295882 [running]:
k8s.io/api/core/v1.(*EnvVarSource).DeepCopyInto(0x0, 0xc00007e580)
        /__w/octant/octant/vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go:1269 +0x5f
k8s.io/api/core/v1.(*EnvVar).DeepCopyInto(0xc000822480, 0xc00102bb00)
        /__w/octant/octant/vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go:1252 +0x9f
k8s.io/api/core/v1.(*Container).DeepCopyInto(0xc0017f7340, 0xc0003702c0)
        /__w/octant/octant/vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go:755 +0x659
k8s.io/api/core/v1.(*PodSpec).DeepCopyInto(0xc000700d18, 0xc000551118)
        /__w/octant/octant/vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go:3810 +0x13f5
k8s.io/api/core/v1.(*Pod).DeepCopyInto(0xc000700c00, 0xc000551000)
        /__w/octant/octant/vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go:3297 +0xd6
k8s.io/api/core/v1.(*Pod).DeepCopy(...)
        /__w/octant/octant/vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go:3308
k8s.io/api/core/v1.(*Pod).DeepCopyObject(0xc000700c00, 0xc00063a000, 0x0)
        /__w/octant/octant/vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go:3314 +0x8a
github.com/vmware-tanzu/octant/internal/modules/overview/yamlviewer.(*yamlViewer).ToComponent(0xc001b9a000, 0xc000700c00, 0xc001b9a000, 0x0)
        /__w/octant/octant/internal/modules/overview/yamlviewer/yamlviewer.go:46 +0x1e3
github.com/vmware-tanzu/octant/internal/modules/overview/yamlviewer.ToComponent(0x7a5dae8, 0xc000700c00, 0x24, 0xc000802060, 0x24)
        /__w/octant/octant/internal/modules/overview/yamlviewer/yamlviewer.go:23 +0xaf
github.com/vmware-tanzu/octant/internal/describer.YAMLViewerTab(0x7a8c360, 0xc001892000, 0x7a5dae8, 0xc000700c00, 0x7ab0408, 0xc0001302d0, 0x7aad548, 0xc00185a580, 0xc0018920c0, 0x7a4d7c0, ...)
        /__w/octant/octant/internal/describer/tab.go:106 +0x45
github.com/vmware-tanzu/octant/internal/describer.ObjectTabsGenerator.Generate.func1(0x0, 0x0)
        /__w/octant/octant/internal/describer/tab_generator.go:82 +0xf9
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000ceca50, 0xc0001a8cc0)
        /__w/octant/octant/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x62
created by golang.org/x/sync/errgroup.(*Group).Go
        /__w/octant/octant/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x71
PS C:\windows\system32>
````

Octant version : 
````
<html>
<body>
<!--StartFragment-->

Version | 0.23.0
-- | --
fbe2be3b687b3e2199ea32753281c9de1f334171
2021-08-02T22:39:02Z

<!--EndFragment-->
</body>
</html>

````

**Comment by wwitzel3** [comment]
Thank you for reporting this! The messages are not related to the component (YAMLViewer) panic. That said, we'll get this fixed up so it is part of the next release.

**Comment by wwitzel3** [comment]
I was unable to replicate this issue with the YAMLViewer component deep copy resulting in a panic. There was something about the PodSpec that was nil that the deep copy call did not like.

If you are able reproduce this error with a specific pod and are able to provide the YAML for that Pod, that would be extremely helpful.

**Comment by survivant** [comment]
I don't have the yaml anymore.. but I'll check if the problem appears again with a new one.

**Comment by survivant** [comment]
I wasn't able to reproduce the issue anymore.  Should we close it ?

**Comment by survivant** [comment]
I got the issue again today

````
PS C:\test-keycloak\keycloak> octant version
Version:  0.24.0
Git commit:  5a8648921cc2779eb62a0ac11147f12aa29f831c
Built:  2021-09-09T01:54:00Z
PS C:\test-keycloak\keycloak>
````


````
W1125 09:04:35.462817   12008 reflector.go:436] /__w/octant/octant/internal/objectstore/dynamic_cache.go:390: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
W1125 09:05:21.414072   12008 reflector.go:436] /__w/octant/octant/internal/objectstore/dynamic_cache.go:390: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x12053bf]

goroutine 6713566 [running]:
k8s.io/api/core/v1.(*EnvVarSource).DeepCopyInto(0x0, 0xc0012465a0)
        /__w/octant/octant/vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go:1269 +0x5f
k8s.io/api/core/v1.(*EnvVar).DeepCopyInto(0xc0011c4410, 0xc0000e6140)
        /__w/octant/octant/vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go:1252 +0x9f
k8s.io/api/core/v1.(*Container).DeepCopyInto(0xc0030c2f20, 0xc0015f86e0)
        /__w/octant/octant/vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go:755 +0x659
k8s.io/api/core/v1.(*PodSpec).DeepCopyInto(0xc000f00d18, 0xc000878d18)
        /__w/octant/octant/vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go:3810 +0x13f5
k8s.io/api/core/v1.(*Pod).DeepCopyInto(0xc000f00c00, 0xc000878c00)
        /__w/octant/octant/vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go:3297 +0xd6
k8s.io/api/core/v1.(*Pod).DeepCopy(...)
        /__w/octant/octant/vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go:3308
k8s.io/api/core/v1.(*Pod).DeepCopyObject(0xc000f00c00, 0xc0008f02d0, 0x0)
        /__w/octant/octant/vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go:3314 +0x8a
github.com/vmware-tanzu/octant/internal/modules/overview/yamlviewer.(*yamlViewer).ToComponent(0xc0088a8b60, 0xc000f00c00, 0xc0088a8b60, 0x0)
        /__w/octant/octant/internal/modules/overview/yamlviewer/yamlviewer.go:46 +0x1e3
github.com/vmware-tanzu/octant/internal/modules/overview/yamlviewer.ToComponent(0x975e9c0, 0xc000f00c00, 0xd, 0xc003fa6050, 0xd)
        /__w/octant/octant/internal/modules/overview/yamlviewer/yamlviewer.go:23 +0xaf
github.com/vmware-tanzu/octant/internal/describer.YAMLViewerTab(0x9790408, 0xc00118f1a0, 0x975e9c0, 0xc000f00c00, 0x97ba3a8, 0xc0003345a0, 0x97b6ca8, 0xc00116f1c0, 0xc00118f260, 0x9748cc0, ...)
        /__w/octant/octant/internal/describer/tab.go:106 +0x45
github.com/vmware-tanzu/octant/internal/describer.ObjectTabsGenerator.Generate.func1(0x0, 0x0)
        /__w/octant/octant/internal/describer/tab_generator.go:82 +0xf9
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0029f02d0, 0xc000f3c3c0)
        /__w/octant/octant/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x62
created by golang.org/x/sync/errgroup.(*Group).Go
        /__w/octant/octant/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x71
PS C:\test-keycloak\keycloak>
````

**Comment by survivant** [comment]
@wwitzel3 

I restarted octant and got again the error on my same pod.  I was in the logs and the error appears

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/191879/143484989-abba0fe6-65ff-4362-8fd9-e3be67c14aba.png">


````
2021-11-25T12:48:33.321-0500    INFO    dash/dash.go:546        Dashboard is available at http://127.0.0.1:7777

W1125 12:48:36.892863   11224 reflector.go:436] /__w/octant/octant/internal/objectstore/dynamic_cache.go:390: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
W1125 12:48:37.799196   11224 reflector.go:436] /__w/octant/octant/internal/objectstore/dynamic_cache.go:390: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
2021-11-25T12:48:38.962-0500    ERROR   api/content_manager.go:159      generate content        {"client-id": "e99fed86-4e17-11ec-a815-00059a3c7a00", "err": "generate content: get volume for key CacheKey[APIVersion='v1', Kind='PersistentVolume', Name='pvc-bc0d4203-4ded-4e7a-afce-33bff0385242']:  \"pvc-bc0d4203-4ded-4e7a-afce-33bff0385242\" not found", "content-path": "overview/namespace/default"}
github.com/vmware-tanzu/octant/internal/api.(*ContentManager).runUpdate.func1
        /__w/octant/octant/internal/api/content_manager.go:159
github.com/vmware-tanzu/octant/internal/api.(*InterruptiblePoller).Run.func1
        /__w/octant/octant/internal/api/poller.go:86
github.com/vmware-tanzu/octant/internal/api.(*InterruptiblePoller).Run
        /__w/octant/octant/internal/api/poller.go:95
github.com/vmware-tanzu/octant/internal/api.(*ContentManager).Start
        /__w/octant/octant/internal/api/content_manager.go:133
W1125 12:48:39.820763   11224 reflector.go:436] /__w/octant/octant/internal/objectstore/dynamic_cache.go:390: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
2021-11-25T12:48:39.985-0500    ERROR   api/content_manager.go:159      generate content        {"client-id": "e99fed86-4e17-11ec-a815-00059a3c7a00", "err": "generate content: get volume for key CacheKey[APIVersion='v1', Kind='PersistentVolume', Name='pvc-bc0d4203-4ded-4e7a-afce-33bff0385242']: persistentvolumes \"pvc-bc0d4203-4ded-4e7a-afce-33bff0385242\" not found", "content-path": "overview/namespace/default"}
github.com/vmware-tanzu/octant/internal/api.(*ContentManager).runUpdate.func1
        /__w/octant/octant/internal/api/content_manager.go:159
github.com/vmware-tanzu/octant/internal/api.(*InterruptiblePoller).Run.func1
        /__w/octant/octant/internal/api/poller.go:86
github.com/vmware-tanzu/octant/internal/api.(*InterruptiblePoller).Run
        /__w/octant/octant/internal/api/poller.go:95
github.com/vmware-tanzu/octant/internal/api.(*ContentManager).Start
        /__w/octant/octant/internal/api/content_manager.go:133
W1125 12:48:44.057615   11224 reflector.go:436] /__w/octant/octant/internal/objectstore/dynamic_cache.go:390: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
W1125 12:48:51.900624   11224 reflector.go:436] /__w/octant/octant/internal/objectstore/dynamic_cache.go:390: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
W1125 12:49:17.217033   11224 reflector.go:436] /__w/octant/octant/internal/objectstore/dynamic_cache.go:390: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x12053bf]

goroutine 7383 [running]:
k8s.io/api/core/v1.(*EnvVarSource).DeepCopyInto(0x0, 0xc000f62780)
        /__w/octant/octant/vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go:1269 +0x5f
k8s.io/api/core/v1.(*EnvVar).DeepCopyInto(0xc00083a1e0, 0xc00062a0f0)
        /__w/octant/octant/vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go:1252 +0x9f
k8s.io/api/core/v1.(*Container).DeepCopyInto(0xc0002fcc60, 0xc0008fbce0)
        /__w/octant/octant/vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go:755 +0x659
k8s.io/api/core/v1.(*PodSpec).DeepCopyInto(0xc00181dd18, 0xc00123cd18)
        /__w/octant/octant/vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go:3810 +0x13f5
k8s.io/api/core/v1.(*Pod).DeepCopyInto(0xc00181dc00, 0xc00123cc00)
        /__w/octant/octant/vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go:3297 +0xd6
k8s.io/api/core/v1.(*Pod).DeepCopy(...)
        /__w/octant/octant/vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go:3308
k8s.io/api/core/v1.(*Pod).DeepCopyObject(0xc00181dc00, 0xc0004e8120, 0x0)
        /__w/octant/octant/vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go:3314 +0x8a
github.com/vmware-tanzu/octant/internal/modules/overview/yamlviewer.(*yamlViewer).ToComponent(0xc0013a6900, 0xc00181dc00, 0xc0013a6900, 0x0)
        /__w/octant/octant/internal/modules/overview/yamlviewer/yamlviewer.go:46 +0x1e3
github.com/vmware-tanzu/octant/internal/modules/overview/yamlviewer.ToComponent(0x975e9c0, 0xc00181dc00, 0xc, 0xc0008c3000, 0xc000a4d9d0)
        /__w/octant/octant/internal/modules/overview/yamlviewer/yamlviewer.go:23 +0xaf
github.com/vmware-tanzu/octant/internal/describer.YAMLViewerTab(0x9790408, 0xc001199a70, 0x975e9c0, 0xc00181dc00, 0x97ba3a8, 0xc000488b40, 0x97b6ca8, 0xc0018034c0, 0xc001199b30, 0x9748cc0, ...)
        /__w/octant/octant/internal/describer/tab.go:106 +0x45
github.com/vmware-tanzu/octant/internal/describer.ObjectTabsGenerator.Generate.func1(0xc0013ebec8, 0x0)
        /__w/octant/octant/internal/describer/tab_generator.go:82 +0xf9
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000f6d7a0, 0xc00121aa80)
        /__w/octant/octant/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x62
created by golang.org/x/sync/errgroup.(*Group).Go
        /__w/octant/octant/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x71
PS C:\test-keycloak\keycloak>

````

````
PS C:\workspace\bidgroup\iep-codec\src\main\resources\keycloak> kubectl get pods
NAME                                       READY   STATUS    RESTARTS      AGE
kafka-cp-kafka-0                           1/1     Running   1 (3d ago)    6d21h
kafka-cp-kafka-rest-754b97f4d6-df9l4       1/1     Running   6 (3d ago)    6d21h
kafka-cp-schema-registry-9784c6b86-4mvkx   1/1     Running   3 (3d ago)    6d21h
kafka-cp-zookeeper-0                       1/1     Running   1 (3d ago)    6d21h
keycloak-0                                 1/1     Running   0             21h
keycloak-postgresql-0                      1/1     Running   0             21h
kubernetes-api-78d79cd646-chn4n            1/1     Running   0             21h
twin-api-service-74964cbc45-xdcm2          1/1     Running   0             22h
twin-neo4j-core-0                          1/1     Running   2 (22h ago)   22h
PS C:\workspace\bidgroup\iep-codec\src\main\resources\keycloak>
````
