### ISSUE TITLE
web-deps step fails on macOS

### ISSUE THREAD

**Issue by alebcay** [vmware-tanzu/octant#3329]
**What steps did you take and what happened:**
I downloaded the 0.25.1 source tarball and attempted to build it with the following steps:
```
go run build.go go-install
go run build.go ci-quick
```

The `go run build.go ci-quick` command produces the following output:
```
npm ERR! Invalid Version: ^3.0.8

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/caleb/.npm/_logs/2022-07-29T19_48_48_000Z-debug-0.log
2022/07/29 15:48:50 web-deps: exit status 1
exit status 1
```

And the contents of that log:
```
0 verbose cli /usr/local/Cellar/node/18.7.0/bin/node /usr/local/bin/npm
1 info using npm@8.15.0
2 info using node@v18.7.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 9ms
6 timing config:load:builtin Completed in 10ms
7 timing config:load:cli Completed in 3ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Volumes/Storage/Developer/octant/octant-0.25.1/web/.npmrc Completed in 0ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:/Users/caleb/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 20ms
19 timing npm:load:configload Completed in 20ms
20 timing npm:load:mkdirpcache Completed in 1ms
21 timing npm:load:mkdirplogs Completed in 0ms
22 verbose title npm ci
23 verbose argv "ci" "--prefer-offline" "--no-audit"
24 timing npm:load:setTitle Completed in 3ms
25 timing config:load:flatten Completed in 3ms
26 timing npm:load:display Completed in 6ms
27 verbose logfile logs-max:10 dir:/Users/caleb/.npm/_logs
28 verbose logfile /Users/caleb/.npm/_logs/2022-07-29T19_48_48_000Z-debug-0.log
29 timing npm:load:logFile Completed in 6ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 37ms
33 timing arborist:ctor Completed in 1ms
34 silly logfile start cleaning logs, removing 1 files
35 silly logfile done cleaning log files
36 timing idealTree:init Completed in 27ms
37 timing idealTree:userRequests Completed in 1ms
38 silly idealTree buildDeps
39 timing idealTree:#root Completed in 0ms
40 silly fetch manifest hosted-git-info@^4.0.2
41 http fetch GET 200 https://registry.npmjs.org/npm 2614ms (cache stale)
42 http fetch GET 200 https://registry.npmjs.org/npm 11ms (cache stale)
43 http fetch GET 200 https://registry.npmjs.org/hosted-git-info 175ms (cache miss)
44 timing idealTree Completed in 219ms
45 timing command:ci Completed in 2745ms
46 verbose stack TypeError: Invalid Version: ^3.0.8
46 verbose stack     at new SemVer (/usr/local/lib/node_modules/npm/node_modules/semver/classes/semver.js:38:13)
46 verbose stack     at compare (/usr/local/lib/node_modules/npm/node_modules/semver/functions/compare.js:3:32)
46 verbose stack     at Object.gte (/usr/local/lib/node_modules/npm/node_modules/semver/functions/gte.js:2:30)
46 verbose stack     at CanPlaceDep.checkCanPlaceCurrent (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/can-place-dep.js:173:51)
46 verbose stack     at CanPlaceDep.checkCanPlace (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/can-place-dep.js:157:27)
46 verbose stack     at new CanPlaceDep (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/can-place-dep.js:114:26)
46 verbose stack     at PlaceDep.place (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:123:19)
46 verbose stack     at new PlaceDep (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:73:10)
46 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:990:31
46 verbose stack     at Array.map (<anonymous>)
47 verbose cwd /Volumes/Storage/Developer/octant/octant-0.25.1/web
48 verbose Darwin 21.5.0
49 verbose node v18.7.0
50 verbose npm  v8.15.0
51 error Invalid Version: ^3.0.8
52 verbose exit 1
53 timing npm Completed in 2886ms
54 verbose unfinished npm timer idealTree:buildDeps 1659124130695
55 verbose unfinished npm timer idealTree:node_modules/app-builder-lib 1659124130699
56 verbose code 1
57 error A complete log of this run can be found in:
57 error     /Users/caleb/.npm/_logs/2022-07-29T19_48_48_000Z-debug-0.log
```

**What did you expect to happen:**
I expected the build to complete successfully and produce an `octant` binary.

**Anything else you would like to add:**
Originally observed when trying to re-build version 0.25.1 in Homebrew, see https://github.com/Homebrew/homebrew-core/pull/106816.

**Environment:**

- Octant version (use `octant version`): 0.25.1
- Kubernetes version (use `kubectl version`): N/A
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):
  - macOS 12 (tried on both Intel and ARM64)
  - Go 1.18.4
  - Tried with both Node 18.7.0 and 16.16.0

**Comment by pauloconnor** [comment]
https://github.com/vmware-tanzu/octant/pull/3311 fixes this, though I had to run `npm i` in the `web` directory. You'll need node 14 configured too.
