### ISSUE TITLE
Unable to access from remote browser

### ISSUE THREAD

**Issue by jdundondev** [vmware-tanzu/octant#417]
I'm trying to connect to Octant from a remote machine (Mac running Chrome). I start Octant on my K8S master node as follows:

$ OCTANT_LISTENER_ADDR=10.25.255.80:8900 octant --disable-open-browser

but it dies with the following message.

Should I be able to do this, and if so, how?

2019-11-08T11:22:49.621-0800	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "overview/serviceEditor", "module-name": "overview"}
2019-11-08T11:22:49.621-0800	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "deployment/configuration", "module-name": "overview"}
2019-11-08T11:22:49.621-0800	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "overview/containerEditor", "module-name": "overview"}
2019-11-08T11:22:49.621-0800	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "octant/deleteObject", "module-name": "configuration"}
2019-11-08T11:22:49.623-0800	INFO	dash/dash.go:370	Using embedded Octant frontend
2019-11-08T11:22:49.630-0800	INFO	dash/dash.go:349	Dashboard is available at http://10.25.255.80:8900

2019-11-08T11:22:54.223-0800	ERROR	api/websocket_service.go:42	create websocket client	{"err": "websocket: request origin not allowed by Upgrader.CheckOrigin"}
github.com/vmware-tanzu/octant/internal/api.serveWebsocket
	/go/src/github.com/vmware-tanzu/octant/internal/api/websocket_service.go:42
github.com/vmware-tanzu/octant/internal/api.websocketService.func1
	/go/src/github.com/vmware-tanzu/octant/internal/api/websocket_service.go:34
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2007
github.com/vmware-tanzu/octant/internal/api.rebindHandler.func1.1
	/go/src/github.com/vmware-tanzu/octant/internal/api/middleware.go:52
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2007
github.com/gorilla/mux.(*Router).ServeHTTP
	/go/pkg/mod/github.com/gorilla/mux@v1.6.2/mux.go:162
github.com/gorilla/mux.(*Router).ServeHTTP
	/go/pkg/mod/github.com/gorilla/mux@v1.6.2/mux.go:162
github.com/gorilla/handlers.(*cors).ServeHTTP
	/go/pkg/mod/github.com/gorilla/handlers@v1.4.0/cors.go:135
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2802
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1890
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x145cbea]

goroutine 126 [running]:
github.com/vmware-tanzu/octant/internal/api.(*WebsocketClient).writePump(0x0)
	/go/src/github.com/vmware-tanzu/octant/internal/api/websocket_client.go:186 +0x9a
created by github.com/vmware-tanzu/octant/internal/api.serveWebsocket
	/go/src/github.com/vmware-tanzu/octant/internal/api/websocket_service.go:47 +0xce
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1463db6]

goroutine 167 [running]:
github.com/vmware-tanzu/octant/internal/api.(*WebsocketClient).readPump.func2(0x0)
	/go/src/github.com/vmware-tanzu/octant/internal/api/websocket_client.go:99 +0x26
created by github.com/vmware-tanzu/octant/internal/api.(*WebsocketClient).readPump
	/go/src/github.com/vmware-tanzu/octant/internal/api/websocket_client.go:98 +0x8e

**Comment by wwitzel3** [comment]
Sorry it tooks me so long to respond, this issue for some reason missed my inbox.

You'll need to also set the the `OCTANT_ACCEPTED_HOSTS`

    OCTANT_ACCEPTED_HOSTS - set to comma-separated string of hosts to be accepted. (e.g. demo.octant.example.com,awesome.octant.zr)

**Comment by wwitzel3** [comment]
You can see the full list of environment variables and flags at https://octant.dev/docs/master/getting-started/

**Comment by wwitzel3** [comment]
Hi @jdundondev just wanted to let you know I'm closing this issue, you can read a full explanation in #450.
