### ISSUE TITLE
Error : "unable to start CRD watcher"

### ISSUE THREAD

**Issue by moderation** [vmware-tanzu/octant#562]
Running a latest master build on a highly restricted cluster I get the following error:

```
build/octant -v --namespace <NAMESPACE> --disable-cluster-overview
2020-01-23T15:49:55.677Z        DEBUG   commands/dash.go:67     disable-open-browser: %!s(bool=false)
2020-01-23T15:49:55.677Z        DEBUG   dash/dash.go:70 Loading configuration: /home/<USERID>/.kube/config
2020-01-23T15:49:55.680Z        DEBUG   cluster/cluster.go:265  initializing REST client configuration  {"client-qps": 200, "client-burst": 400}
2020-01-23T15:49:55.680Z        DEBUG   cluster/cluster.go:108  created temp directory  {"component": "cluster client", "dir": "/home/<USERID>/Library/cache/octant494091269"}
2020-01-23T15:49:55.680Z        DEBUG   dash/dash.go:98 initial namespace for dashboard is <NAMESPACE>
2020-01-23T15:49:56.039Z        ERROR   commands/dash.go:109    dashboard failed        {"err": "unable to start CRD watcher"}
github.com/vmware-tanzu/octant/internal/commands.newOctantCmd.func1.2
        /home/<USERID>/Library/octant/internal/commands/dash.go:109
```

Is this an error in the build itself or as a result of not being able to list CRDs from an RBAC perspective? Running on RHEL 7 Linux.

**Comment by wwitzel3** [comment]
I've opened #563 which will give better insight in to what the actual error is. We were not wrapping the error that was coming back and instead just printing an entirely new error message which removes all of the useful information about what is causing the error.

**Comment by moderation** [comment]
Thanks for the quick turnaround. Here is the updated error:
```
build/octant -v --namespace <NAMESPACE> --disable-cluster-overview
2020-01-23T19:32:56.301Z        DEBUG   commands/dash.go:67     disable-open-browser: %!s(bool=false)
2020-01-23T19:32:56.302Z        DEBUG   dash/dash.go:69 Loading configuration: /home/<USERID>/.kube/config
2020-01-23T19:32:56.304Z        DEBUG   cluster/cluster.go:265  initializing REST client configuration  {"client-qps": 200, "client-burst": 400}
2020-01-23T19:32:56.305Z        DEBUG   cluster/cluster.go:108  created temp directory  {"component": "cluster client", "dir": "/home/<USERID>/Library/cache/octant088918540"}
2020-01-23T19:32:56.305Z        DEBUG   dash/dash.go:97 initial namespace for dashboard is <NAMESPACE>
2020-01-23T19:32:56.812Z        ERROR   commands/dash.go:109    dashboard failed        {"err": "unable to start CRD watcher: crd watcher has failed: check access to watch CacheKey[APIVersion='apiextensions.k8s.io/v1beta1', Kind='CustomResourceDefinition']: watch: CacheKey[APIVersion='apiextensions.k8s.io/v1beta1', Kind='CustomResourceDefinition']: %!s(<nil>)"}
github.com/vmware-tanzu/octant/internal/commands.newOctantCmd.func1.2
        /home/<USERID>/Library/octant/internal/commands/dash.go:109        
```
Keep in mind that the developer doesn't have the ability to `kubectl get crd`. Returns:
```
Error from server (Forbidden): customresourcedefinitions.apiextensions.k8s.io is forbidden: User "<USERID>@<DOMAIN>" cannot list resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
```

**Comment by wwitzel3** [comment]
Yeah, this looks like a regression maybe, or it was never working right in the first place, access errors are supposed to be logged and the starting of the watcher skipped.

**Comment by wwitzel3** [comment]
@moderation are you able to build from my branch to see if it gets you past this error?

https://github.com/wwitzel3/octant/tree/issue-562

**Comment by moderation** [comment]
@wwitzel3 still fails to start. Details below:
```
git status
On branch issue-562
nothing to commit, working tree clean

env OCTANT_LISTENER_ADDR=127.0.0.1:8900 build/octant -v --namespace <NAMESPACE> --disable-cluster-overview
2020-01-24T20:25:03.007Z        DEBUG   commands/dash.go:67     disable-open-browser: %!s(bool=false)
2020-01-24T20:25:03.007Z        DEBUG   dash/dash.go:69 Loading configuration: /home/<USERID>/.kube/config
2020-01-24T20:25:03.033Z        DEBUG   cluster/cluster.go:265  initializing REST client configuration  {"client-qps": 200, "client-burst": 400}
2020-01-24T20:25:03.034Z        DEBUG   cluster/cluster.go:108  created temp directory  {"component": "cluster client", "dir": "/home/<USERID>/Library/cache/octant082578322"}
2020-01-24T20:25:03.034Z        DEBUG   dash/dash.go:97 initial namespace for dashboard is <NAMESPACE>
2020-01-24T20:25:05.889Z        ERROR   commands/dash.go:109    dashboard failed        {"err": "unable to start CRD watcher: crd watcher has failed: check access to watch CacheKey[APIVersion='apiextensions.k8s.io/v1beta1', Kind='CustomResourceDefinition']: watch: CacheKey[APIVersion='apiextensions.k8s.io/v1beta1', Kind='CustomResourceDefinition']: %!s(<nil>)"}
github.com/vmware-tanzu/octant/internal/commands.newOctantCmd.func1.2
        /home/<USERID>/Library/octant_test/octant/internal/commands/dash.go:109
```

**Comment by wwitzel3** [comment]
I changed the formatting of the error message in the PR and it appears that the output is still using the old error message format. Can you re-run the build command and provide the output of `octant version`

**Comment by wwitzel3** [comment]
I would expect the output to be

```Version:  (dev-version)
Git commit:  81e55320```

**Comment by moderation** [comment]
```
git log -n 1 --oneline
81e55320 (HEAD -> issue-562, origin/issue-562) fix AccessError type assertion in CRD watcher
```
```
build/octant version
Version:  (dev-version)
Git commit:  81e55320
Built:  2020-01-24T20:50:38Z
```
```
env OCTANT_LISTENER_ADDR=127.0.0.1:8900 build/octant -v --namespace <NAMESPACE> --disable-cluster-overview
2020-01-24T20:55:21.368Z        DEBUG   commands/dash.go:67     disable-open-browser: %!s(bool=false)
2020-01-24T20:55:21.368Z        DEBUG   dash/dash.go:69 Loading configuration: /home/<USERID>/.kube/config
2020-01-24T20:55:21.370Z        DEBUG   cluster/cluster.go:265  initializing REST client configuration  {"client-qps": 200, "client-burst": 400}
2020-01-24T20:55:21.371Z        DEBUG   cluster/cluster.go:108  created temp directory  {"component": "cluster client", "dir": "/home/<USERID>/Library/cache/octant493982554"}
2020-01-24T20:55:21.371Z        DEBUG   dash/dash.go:97 initial namespace for dashboard is <NAMESPACE>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x137e5c5]

goroutine 11 [running]:
github.com/vmware-tanzu/octant/internal/errors.(*AccessError).Error(0xc00013e090, 0xc000236d30, 0xc00074da08)
        /home/<USERID>/Library/octant_test/octant/internal/errors/access_error.go:47 +0x45
github.com/vmware-tanzu/octant/internal/log.(*sugaredLogWrapper).WithErr(0xc0001300b8, 0x2546f80, 0xc00013e090, 0xc000672100, 0x1)
        /home/<USERID>/Library/octant_test/octant/internal/log/logger.go:45 +0x35
github.com/vmware-tanzu/octant/internal/describer.(*DefaultCRDWatcher).Watch(0xc00037eec0, 0x2588780, 0xc0005c7a70, 0xc000231480, 0x25a76c0)
        /home/<USERID>/Library/octant_test/octant/internal/describer/crd_watcher.go:142 +0x3a5
github.com/vmware-tanzu/octant/pkg/dash.Run(0x25886c0, 0xc000566880, 0x259d520, 0xc0001300b8, 0xc000048230, 0x100, 0xc000041440, 0x1a, 0x7ffcd457ce32, 0x12, ...)
        /home/<USERID>/Library/octant_test/octant/pkg/dash/dash.go:114 +0x746
github.com/vmware-tanzu/octant/internal/commands.newOctantCmd.func1.2(0x19b49d9, 0xd, 0x25886c0, 0xc000566880, 0x259d520, 0xc0001300b8, 0xc000048230, 0xc0000481c0)
        /home/<USERID>/Library/octant_test/octant/internal/commands/dash.go:108 +0x5e3
created by github.com/vmware-tanzu/octant/internal/commands.newOctantCmd.func1
        /home/<USERID>/Library/octant_test/octant/internal/commands/dash.go:73 +0x518
```

**Comment by wwitzel3** [comment]
I see the issue, sometimes the `err` that the `AccessError` wraps can be nil. I pushed up a fix to the PR.
