### ISSUE TITLE
panic: runtime error: slice bounds out of range [:-1]

### ISSUE THREAD

**Issue by Rurouni** [vmware-tanzu/octant#584]
When opening new workloads UI octant process crashes with:

```
panic: runtime error: slice bounds out of range [:-1]

goroutine 33783 [running]:
github.com/vmware-tanzu/octant/internal/api.notFoundRedirectPath(0xc0000362c0, 0x20, 0x25, 0x0)
        /go/src/github.com/vmware-tanzu/octant/internal/api/stream.go:39 +0x170
github.com/vmware-tanzu/octant/internal/api.(*ContentManager).generateContent(0xc000fd6c00, 0x25eadc0, 0xc000f10340, 0x26174a0, 0xc000229e40, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/vmware-tanzu/octant/internal/api/content_manager.go:136 +0x3f4
github.com/vmware-tanzu/octant/internal/api.(*ContentManager).runUpdate.func1(0x25eadc0, 0xc000f10340, 0x0)
        /go/src/github.com/vmware-tanzu/octant/internal/api/content_manager.go:98 +0x109
github.com/vmware-tanzu/octant/internal/api.(*job).run.func1(0xc000fca570, 0xc000e2a4d0)
        /go/src/github.com/vmware-tanzu/octant/internal/api/poller.go:111 +0x43
created by github.com/vmware-tanzu/octant/internal/api.(*job).run
        /go/src/github.com/vmware-tanzu/octant/internal/api/poller.go:110 +0x95

```
>octant.exe version

Version:  0.10.0
Git commit:  72e66943d660dc7bdd2c96b27cc141f9c4e8f9d8
Built:  2020-01-24T00:55:30Z

Environment: win 10 (1903)

**Comment by wwitzel3** [comment]
Fixed in #571 will be part of 0.10.1 release
