### ISSUE TITLE
 websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header

### ISSUE THREAD

**Issue by sachinrase** [vmware-tanzu/octant#758]
getting this error while running behind a lb  using octant-0.10.2-1.x86_64

```
2020-03-08T18:30:27.348-0700	INFO	dash/watcher.go:116	watching config file	{"component": "config-watcher", "config": "./config"}
2020-03-08T18:30:27.350-0700	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "overview/startPortForward", "module-name": "overview"}
2020-03-08T18:30:27.350-0700	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "overview/stopPortForward", "module-name": "overview"}
2020-03-08T18:30:27.350-0700	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "overview/commandExec", "module-name": "overview"}
2020-03-08T18:30:27.350-0700	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "overview/deleteTerminal", "module-name": "overview"}
2020-03-08T18:30:27.350-0700	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "deployment/configuration", "module-name": "overview"}
2020-03-08T18:30:27.350-0700	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "overview/containerEditor", "module-name": "overview"}
2020-03-08T18:30:27.350-0700	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "overview/serviceEditor", "module-name": "overview"}
2020-03-08T18:30:27.350-0700	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "octant/deleteObject", "module-name": "configuration"}
2020-03-08T18:30:27.530-0700	INFO	dash/dash.go:404	Using embedded Octant frontend
2020-03-08T18:30:27.534-0700	INFO	dash/dash.go:383	Dashboard is available at http://0.0.0.0:7777

2020-03-08T18:30:32.049-0700	ERROR	api/websocket_service.go:42	create websocket client	{"err": "websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header"}
github.com/vmware-tanzu/octant/internal/api.serveWebsocket
	/go/src/github.com/vmware-tanzu/octant/internal/api/websocket_service.go:42
github.com/vmware-tanzu/octant/internal/api.websocketService.func1
	/go/src/github.com/vmware-tanzu/octant/internal/api/websocket_service.go:34
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2007
github.com/vmware-tanzu/octant/internal/api.rebindHandler.func1.1
	/go/src/github.com/vmware-tanzu/octant/internal/api/middleware.go:118
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2007
github.com/gorilla/mux.(*Router).ServeHTTP
	/go/pkg/mod/github.com/gorilla/mux@v1.6.2/mux.go:162
github.com/gorilla/mux.(*Router).ServeHTTP
	/go/pkg/mod/github.com/gorilla/mux@v1.6.2/mux.go:162
github.com/gorilla/handlers.(*cors).ServeHTTP
	/go/pkg/mod/github.com/gorilla/handlers@v1.4.0/cors.go:135
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2802
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1890
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x14875d5]

goroutine 205 [running]:
github.com/vmware-tanzu/octant/internal/api.(*WebsocketClient).readPump.func1(0x0)
	/go/src/github.com/vmware-tanzu/octant/internal/api/websocket_client.go:97 +0x5
panic(0x1782a60, 0x322b7c0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/vmware-tanzu/octant/internal/api.(*WebsocketClient).readPump(0x0)
	/go/src/github.com/vmware-tanzu/octant/internal/api/websocket_client.go:108 +0x96
created by github.com/vmware-tanzu/octant/internal/api.serveWebsocket
	/go/src/github.com/vmware-tanzu/octant/internal/api/websocket_service.go:46 +0xac
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1487606]

goroutine 505 [running]:
github.com/vmware-tanzu/octant/internal/api.(*WebsocketClient).readPump.func2(0x0)
	/go/src/github.com/vmware-tanzu/octant/internal/api/websocket_client.go:101 +0x26
created by github.com/vmware-tanzu/octant/internal/api.(*WebsocketClient).readPump
	/go/src/github.com/vmware-tanzu/octant/internal/api/websocket_client.go:100 +0x8e
```

**Comment by sachinrase** [comment]
It was web socket issue , LB needed websocket option enabled

**Comment by ysaakpr** [comment]
getting same error, what do you mean by lb ? i am using aws elb and it works with other was services
My request flows like this
ELB > NGINX-INGRESS (With was) > oauthproxy > octant.
