### ISSUE TITLE
Click on a PVC results in a stacktrace

### ISSUE THREAD

**Issue by rodrigc** [vmware-tanzu/octant#814]
**What steps did you take and what happened:**
I used octant to browse my cluster.  When I clicked on a PVC (specifically I clicked on the **Volume** field of the PVC)  I got a stacktrace:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x2129a21]

goroutine 212 [running]:
github.com/vmware-tanzu/octant/internal/printer.(*PersistentVolumeConfiguration).Create(0xc0009bc550, 0x0, 0x3bca540, 0xc000f42680, 0x3baa9c0, 0xc000a4c040, 0x2125804, 0x2516700, 0xc0010c2800)
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/printer/persistentvolume.go:163 +0x6e1
github.com/vmware-tanzu/octant/internal/printer.defaultPersistentVolumeConfig(0xc000140a00, 0x0, 0x3bca540, 0xc000f42680, 0x3baa9c0, 0xc000a4c040, 0x245eea0, 0xc00024a880, 0x0)
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/printer/persistentvolume.go:127 +0x63
github.com/vmware-tanzu/octant/internal/printer.(*persistentVolumeHandler).Config(0xc00024a880, 0x0, 0x3bca540, 0xc000f42680, 0x3baa9c0, 0xc000a4c040, 0x2415800, 0xc000f0fa80)
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/printer/persistentvolume.go:109 +0x54
github.com/vmware-tanzu/octant/internal/printer.PersistentVolumeHandler(0x3baa600, 0xc000f0fa80, 0xc000140a00, 0x0, 0x3bca540, 0xc000f42680, 0x3baa9c0, 0xc000a4c040, 0x0, 0x0, ...)
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/printer/persistentvolume.go:72 +0xc1
reflect.Value.call(0x236b920, 0x39a0168, 0x13, 0x258603e, 0x4, 0xc0009bcab8, 0x3, 0x3, 0x100bebf, 0x2421140, ...)
	/usr/local/Cellar/go/1.14.1/libexec/src/reflect/value.go:460 +0x8ab
reflect.Value.Call(0x236b920, 0x39a0168, 0x13, 0xc0009bcab8, 0x3, 0x3, 0x10198de, 0x4fa76d0, 0x0)
	/usr/local/Cellar/go/1.14.1/libexec/src/reflect/value.go:321 +0xb4
github.com/vmware-tanzu/octant/internal/printer.(*Resource).Print(0xc00024a080, 0x3baa600, 0xc000f0fa80, 0x3b7b300, 0xc000140a00, 0x3baaa00, 0xc0004f6630, 0x23ea3c0, 0xc0009bcbc8, 0xc0009bcbf8, ...)
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/printer/printer.go:77 +0x472
github.com/vmware-tanzu/octant/internal/describer.(*Object).addSummaryTab(0xc000f872c0, 0x3baa600, 0xc000f0fa80, 0x3b7b300, 0xc000140a00, 0xc00018e8c0, 0x3bca540, 0xc000f42680, 0x3bc55a0, 0xc000b30040, ...)
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/describer/object.go:214 +0xab
github.com/vmware-tanzu/octant/internal/describer.(*Object).Describe(0xc000f872c0, 0x3baa600, 0xc000f0fa80, 0x0, 0x0, 0x3bca540, 0xc000f42680, 0x3bc55a0, 0xc000b30040, 0xc000c7a150, ...)
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/describer/object.go:154 +0xf52
github.com/vmware-tanzu/octant/internal/modules/clusteroverview.(*ClusterOverview).Content(0xc0010c5080, 0x3baa600, 0xc000f0fa80, 0xc0008f4420, 0x3c, 0xc000a4c010, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/modules/clusteroverview/clusteroverview.go:167 +0x750
github.com/vmware-tanzu/octant/internal/api.(*ContentManager).generateContent(0xc000f71440, 0x3baa600, 0xc000f0fa80, 0x3bc91e0, 0xc00015ac60, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/api/content_manager.go:161 +0x320
github.com/vmware-tanzu/octant/internal/api.(*ContentManager).runUpdate.func1(0x3baa600, 0xc000f0fa80, 0x485b560)
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/api/content_manager.go:115 +0xe0
github.com/vmware-tanzu/octant/internal/api.(*InterruptiblePoller).Run.func1(0x3baa600, 0xc000f71400, 0x3bbae80, 0xc000010a10, 0xc0009bde77, 0xc000f015c0, 0xc0010b2050, 0xc000810390, 0x3b9aca00)
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/api/poller.go:86 +0x271
github.com/vmware-tanzu/octant/internal/api.(*InterruptiblePoller).Run(0xc001220b30, 0x3baa600, 0xc000f71400, 0xc000f015c0, 0xc000810390, 0x3b9aca00)
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/api/poller.go:95 +0x2ff
github.com/vmware-tanzu/octant/internal/api.(*ContentManager).Start(0xc000f71440, 0x3baa600, 0xc000f71400, 0x3bc91e0, 0xc00015ac60, 0x3b78cc0, 0xc000272d80)
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/api/content_manager.go:105 +0x1c7
created by github.com/vmware-tanzu/octant/internal/api.(*WebsocketState).Start
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/api/websocket_state.go:142 +0x9b
```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Octant version (use `octant version`): 
Version:  0.11.1
Git commit:  a5f7847a7e21d781fdb7edd5389b04edc2ca6b87
Built:  2020-03-30T19:51:23Z

- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T23:41:24Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):

macOS 10.5.3

**Comment by GuessWhoSamFoo** [comment]
Can you provide more information via `kubectl get <resource> <resource-name>`? The stack trace suggests it was a persistent volume and has something to do with the hostpath.

**Comment by rodrigc** [comment]
I did some debugging and found that the exception is happening on this line:

https://github.com/vmware-tanzu/octant/blob/9c246b4ceec1840451546439c18890f70c1c0658/internal/printer/persistentvolume.go#L163

```
	sections.AddText("Host Path", pv.Spec.HostPath.Path)
```

**Comment by rodrigc** [comment]
I built octant and put some printf statements to see what was nil, and got this:

```
pv: &PersistentVolume{ObjectMeta:{pvc-98cdcc24-9c8d-11e9-be6a-000c29b121a5   /api/v1/persistentvolumes/pvc-98cdcc24-9c8d-11e9-be6a-000c29b121a5 9b517b77-9c8d-11e9-be6a-000c29b121a5 1326584 0 2019-07-01 22:52:42 -0700 PDT <nil> <nil> map[] map[kubernetes.io/createdby:portworx-volume-dynamic-provisioner pv.kubernetes.io/bound-by-controller:yes pv.kubernetes.io/provisioned-by:kubernetes.io/portworx-volume] [] [kubernetes.io/pv-protection]  []},Spec:PersistentVolumeSpec{Capacity:ResourceList{storage: {{10737418240 0} {<nil>} 10Gi BinarySI},},PersistentVolumeSource:PersistentVolumeSource{GCEPersistentDisk:nil,AWSElasticBlockStore:nil,HostPath:nil,Glusterfs:nil,NFS:nil,RBD:nil,ISCSI:nil,Cinder:nil,CephFS:nil,FC:nil,Flocker:nil,FlexVolume:nil,AzureFile:nil,VsphereVolume:nil,Quobyte:nil,AzureDisk:nil,PhotonPersistentDisk:nil,PortworxVolume:&PortworxVolumeSource{VolumeID:407376759422263411,FSType:,ReadOnly:false,},ScaleIO:nil,Local:nil,StorageOS:nil,CSI:nil,},AccessModes:[ReadWriteMany],ClaimRef:&ObjectReference{Kind:PersistentVolumeClaim,Namespace:jenkins,Name:jenkins-home-jenkins-master-0,UID:98cdcc24-9c8d-11e9-be6a-000c29b121a5,APIVersion:v1,ResourceVersion:1326558,FieldPath:,},PersistentVolumeReclaimPolicy:Delete,StorageClassName:px-repl3-shared,MountOptions:[],VolumeMode:*Filesystem,NodeAffinity:nil,},Status:PersistentVolumeStatus{Phase:Bound,Message:,Reason:,},}

pv.Spec: {map[storage:{{10737418240 0} {<nil>} 10Gi BinarySI}] {nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil &PortworxVolumeSource{VolumeID:407376759422263411,FSType:,ReadOnly:false,} nil nil nil nil} [ReadWriteMany] &ObjectReference{Kind:PersistentVolumeClaim,Namespace:jenkins,Name:jenkins-home-jenkins-master-0,UID:98cdcc24-9c8d-11e9-be6a-000c29b121a5,APIVersion:v1,ResourceVersion:1326558,FieldPath:,} Delete px-repl3-shared [] 0xc000f2c5a0 nil}

pv.Spec.HostPath: nil
```

**Comment by rodrigc** [comment]
```
kubectl -n jenkins get pvc jenkins-home-jenkins-master-0 -o yaml
```

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-class: px-repl3-shared
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/portworx-volume
  creationTimestamp: "2019-07-02T05:52:37Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    name: jenkins-master
  name: jenkins-home-jenkins-master-0
  namespace: jenkins
  resourceVersion: "1326585"
  selfLink: /api/v1/namespaces/jenkins/persistentvolumeclaims/jenkins-home-jenkins-master-0
  uid: 98cdcc24-9c8d-11e9-be6a-000c29b121a5
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  volumeName: pvc-98cdcc24-9c8d-11e9-be6a-000c29b121a5
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  phase: Bound
```

**Comment by GuessWhoSamFoo** [comment]
The issue is that it assumes the volume source to be `HostPath`. It will need to be updated to be a giant switch statement of possible types similar to handling in `volume.go`
